### ISSUE TITLE
A feature request to add Coindrop button to GitHub README.md

### ISSUE THREAD

**Issue by hakerdefo** [markjackson02/coindrop#77]
As the title says here is a feature request to create a Coindrop button that can be integrated into to GitHub's README.md page. Something along these lines for example,
https://help.ko-fi.com/hc/en-us/articles/360021025553-How-to-Add-a-Ko-fi-Button-to-GitHub

Cheers!!!

**Comment by markjackson02** [comment]
There is an HTML Button you can embed. On your Coindrop page, click Share, then Button, and copy the HTML code for the button. Let me know if that works for you?

**Comment by markjackson02** [comment]
I updated the Coindrop README.md with an example of how to embed the button: https://github.com/markjackson02/coindrop#whenwhere-to-use-it-

Let me know if you have any other questions or issues. Thanks!

**Comment by hakerdefo** [comment]
Thank you @markjackson02 for the help.

Cheers!!!

**Comment by hakerdefo** [comment]
Works like a charm. Here it is in action in one of my GitHub project,
https://github.com/hakerdefo/cmus-lyrics

Thanks & cheers!!!
